# Generated by Django 3.0.5 on 2020-04-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=99)),
                ('lastname', models.CharField(max_length=99)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='testing_app.Flight')),
            ],
        ),
    ]
